### ISSUE TITLE
Colour Picker Doesn’t Work (Option Page → Advanced)

### ISSUE THREAD

**Issue by cnieuweboer** [easonwong-de/Adaptive-Tab-Bar-Colour#49]
When setting a color for a specific domain the color picker doesn't work properly. The only the first character entered in the R, G or B textboxes is saved. So to enter a value in those, the color picker has to be closed and opened again for every character.

**Comment by easonwong-de** [comment]
@cnieuweboer Thanks for reporting the issue, are you using Windows 10? It seems like a common issue with Windows 10.

**Comment by cnieuweboer** [comment]
I am using Windows 11.

**Comment by easonwong-de** [comment]
@cnieuweboer @jathek I can replicate the bug now. I’ll fix it soon.

**Comment by easonwong-de** [comment]
Hi, @cnieuweboer! I hope you are still around, and I’m more than exciting to tell you that the bug should be fixed now.
