### ISSUE TITLE
Color fade over time... 

### ISSUE THREAD

**Issue by XeonG** [easonwong-de/Adaptive-Tab-Bar-Colour#53]
or somewhere to apply an active css style to a tab and control the style change over time once that is no longer the active tab....

like after 2-5mins the color/style state will go back to match all the other tabs... stuff like that.. don't really care about tabs looking like the website most websites look like shit anyway. especially the guardian what garbage news site that is

**Comment by easonwong-de** [comment]
@XeonG Hi, thanks for the idea. But I’m not sure what does “the color/style state will go back to match all the other tabs” mean. I don’t know exactly how should the tab bar colour match multiple tabs at the same time. Could you please elaborate on that?

**Comment by XeonG** [comment]
I mean after a set time.. the tab that was active and has faded just back to default .. ie however it looked normally..

so active selected tab would have a certain style.. then when you're selected another tab that previous tab would start to fade back to default state over a certain time.. 

its just cus I have often like 70+ tabs opened.. . and often jump from one to another one on the other side of the tabbar.. it's hard to find the exact same tab I was on previously going by just an icon (of which there maybe many similar ones near that last active tab) so having some sort of coloring fading going over time from previously selected tabs would help make those recently view tabs stand out more from all the tabs I hadn't viewed in a while..

There used to be such a addon for Firefox that did exactly this years ago if I remember correctly.. before mozilla screwed up all the addons in order to become a chrome clone following gimped web api extension format, that still seems to limit what firefox addons can do anymore.

**Comment by easonwong-de** [comment]
I think I get what you mean. I think a CSS theme can achieve this effect.
