### ISSUE TITLE
Wider Range for Brightness Sliders Under Customisation Tab

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [easonwong-de/Adaptive-Tab-Bar-Colour#57]
On Firefox Add-Ons site I saw Mozilla made some official Firefox themes, so I hope it would be awesome if you can make even more flexibility in your extension so users can customize the interface to reach similar effects as these:

[![Snap-Crab-No-Name-2023-7-12-0-39-40-No-00](https://i.postimg.cc/B8g9xWYB/Snap-Crab-No-Name-2023-7-12-0-39-40-No-00.png)](https://postimg.cc/B8g9xWYB)
[![Snap-Crab-No-Name-2023-7-12-0-40-49-No-00](https://i.postimg.cc/dhPzpQg9/Snap-Crab-No-Name-2023-7-12-0-40-49-No-00.png)](https://postimg.cc/dhPzpQg9)
[![Snap-Crab-No-Name-2023-7-12-0-42-8-No-00](https://i.postimg.cc/Yhm5dLD9/Snap-Crab-No-Name-2023-7-12-0-42-8-No-00.png)](https://postimg.cc/Yhm5dLD9)

**Comment by KrasnayaPloshchad** [comment]
See https://addons.mozilla.org/firefox/user/4757633/ for more details.

**Comment by easonwong-de** [comment]
@KrasnayaPloshchad I’m not sure if I understand you correctly. By “similar effects”, do you mean configurations like these?

<img width="80%" alt="temp" src="https://github.com/easonwong-de/Adaptive-Tab-Bar-Color/assets/16183548/475c8654-ab99-4a69-9888-5340caabc915">

**Comment by KrasnayaPloshchad** [comment]
Yeah I did, but I feel not satisfied, at least the users should allow to configure using even brighter shades, as Mozilla shown above.

**Comment by easonwong-de** [comment]
Do you mean “there should be more configurable items”, or “the brightness sliders should include a wider range of values”?

**Comment by KrasnayaPloshchad** [comment]
OK, I hope the brightness sliders should include a wider range of values. Maybe even darmness values could be included as well.

**Comment by easonwong-de** [comment]
Thanks for the clarification. I’ll consider it.

**Comment by easonwong-de** [comment]
Hi, @KrasnayaPloshchad. I increased the shade range to -50% to +50% (percentage to white & black). If you would like to suggest any refinement, feel free to re-open the issue!
