### ISSUE TITLE
Modifiable Light/Dark Threshold

### ISSUE THREAD

**Issue by CennoxX** [easonwong-de/Adaptive-Tab-Bar-Colour#58]
Currently brightness thresold is calculated by brightness = 0.299 × r + 0.587 × g + 0.114 × b; if brightness > 128, then color is bright; otherwise is it dark. 
![grafik](https://github.com/easonwong-de/Adaptive-Tab-Bar-Color/assets/6975881/4e3dbf9e-c3e2-41f9-8e80-9e49eab1522e)
But it seems, the threshold of dark/light color does not work out for everyone. For me, the contrast here isn't enough, for others it might be. So a better option could be to make a setting to set the brightness threshold of currently 128 in the settings

**Comment by easonwong-de** [comment]
This feature will be added. Thanks for the suggestion.

**Comment by KunjanChauhan** [comment]
with the dark themes, i find the contrast between active and no-active tabs is missing.  Can the contrast be increased by a user selectable slider or similar?  also the same parameters should apply to the STG or Siple Tab Groups add on for consistency and usability.  ty.

**Comment by CennoxX** [comment]
> with the dark themes, i find the contrast between active and no-active tabs is missing. Can the contrast be increased by a user selectable slider or similar? also the same parameters should apply to the STG or Siple Tab Groups add on for consistency and usability. ty.

@KunjanChauhan  Please create an own issue if it's not related to tis one.

**Comment by easonwong-de** [comment]
Solved in #29.
