### ISSUE TITLE
Minimum color for the sliders on the customization tab should be darker

### ISSUE THREAD

**Issue by Gooberpatrol66** [easonwong-de/Adaptive-Tab-Bar-Colour#64]
The darkest setting for the sliders seems to be equivalent to the color of the website header, so that the UI appears seamless with the header. I'd like to make parts of the UI (like the tab bar background) darker than the website.

**Comment by easonwong-de** [comment]
Hi, @Gooberpatrol66, @ricab! A new version of ATBC (v2.2) is awaiting review and will be out soon. In the new version, the sliders’ range will be increased.
