### ISSUE TITLE
increase contrast

### ISSUE THREAD

**Issue by KunjanChauhan** [easonwong-de/Adaptive-Tab-Bar-Colour#65]
Using the dark theme, I find the contrast is low in the following areas:

1. contrast between active tab and other passive tabs in the tab bar
2. contrast between active tab and other passive tabs in the the add-on Simple Tab Groups (not sure if this can be changed by Adaptive-Tab-Bar-Colour  add-on)

The lack of contrast results in the user hunting for the tab.

the ideal would be to allow user control to change contrast level and/or to use a different colour altogether for the active tab.

TY.

**Comment by easonwong-de** [comment]
Hello! To increase the contrast between active tab and other tabs, you may try adjusting “selected tab” slider under the “customisation” tab in the add-on’s settings page.
![Screenshot 2024-02-12 at 17 24 31](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/16183548/66cf19b7-5c60-4bf8-b83c-9506713f7919)
The colour scheme of the Simple Tab Group UI could not be changed by Adaptive Tab Bar Colour.
Hope it helps!
