### ISSUE TITLE
New Tab Color

### ISSUE THREAD

**Issue by Redoxahmii** [easonwong-de/Adaptive-Tab-Bar-Colour#70]
I cannot seem to change the New Tab color which is i think named as Home Page color in the preferences of this extension.
No matter what i provide there the default firefox color shows when i open a new tab which i want to change.
Any help is appreciated.

**Comment by easonwong-de** [comment]
@Redoxahmii Interesting. The new tab should have the home page colour if everything goes well. Could you show your add-on settings?

**Comment by Redoxahmii** [comment]
![Screenshot from 2024-02-12 19-42-32](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/13983258/068ceb3a-bab8-4a81-8116-970bfd5242cb)
![Screenshot from 2024-02-12 19-43-10](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/13983258/00eac090-651e-41e2-be38-8248faa32800)

These are the extensions that are enabled and the settings that are enabled in Firefox

**Comment by easonwong-de** [comment]
@Redoxahmii It seems like you’re using Tabliss for new tab. In that case, you may go to a new tab, open the ATBC pop-up menu, and click “specify a colour”. After that, you can set up a colour for the Tabliss new tab.

**Comment by Redoxahmii** [comment]
> @Redoxahmii It seems like you’re using Tabliss for new tab. In that case, you may go to a new tab, open the ATBC pop-up menu, and click “specify a colour”. After that, you can set up a colour for the Tabliss new tab.

I have no clue what ATBC pop-up menu is.

![Screenshot from 2024-02-13 01-18-39](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/13983258/ced2da6c-0da2-4df8-8f14-ed9c5f402223)

i did set this to a solid color but that does not seem to work Screenshots for it would help.

**Comment by easonwong-de** [comment]
Hello. You may click the ATBC icon on your toolbar:
![Screenshot 2024-02-12 at 21 38 12](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/16183548/4b75913c-452f-4725-8ca2-44ba870eea46)

**Comment by Redoxahmii** [comment]
> Hello. You may click the ATBC icon on your toolbar: ![Screenshot 2024-02-12 at 21 38 12](https://private-user-images.githubusercontent.com/16183548/304217328-4b75913c-452f-4725-8ca2-44ba870eea46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NzQwMTUsIm5iZiI6MTcwNzc3MzcxNSwicGF0aCI6Ii8xNjE4MzU0OC8zMDQyMTczMjgtNGI3NTkxM2MtNDUyZi00NzI1LThjYTItNDRiYTg3MGVlYTQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDIxMzUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3M2RmNDI5YWYxNjk1MmFlNzhiMGY0Zjk2ZGRiYzc3ZmM4YzczZTgyOTFkODVkMzEyMmRmMmUwM2ZhYjkxMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9gBK4BrGooDwRB42hhzQk1P1fb9OjWDr2B3e9q1KxXg)

Thank you for guiding. I did try to add manually before and did not seem to work that way so i might have miss-typed the URL in some sense.
