### ISSUE TITLE
Add support for wildcard domains

### ISSUE THREAD

**Issue by sergi0g** [easonwong-de/Adaptive-Tab-Bar-Colour#71]
In the advanced options, where users can specify rules for specific domains, it would be very useful to add support for wildcard subdomains (e.g. `*.stackexchange.com`). This helps avoid the creation of rules for each subdomain of a website when they are all similar.

**Comment by easonwong-de** [comment]
Hi, @sergi0g, v2.2 will support regex in the site list. Currently, it’s awaiting review.
