### ISSUE TITLE
How to avoid getting flashbanged by sites with colorful themes?

### ISSUE THREAD

**Issue by bensaine** [easonwong-de/Adaptive-Tab-Bar-Colour#74]
First of all, I love this extension. Thank you so much for making it. 

The only issue I have with it is that sometimes I get 'flashbanged' by sites with colorful themes. As a dark mode user, the sudden change to a bright colour can be very disturbing, especially late at night, making that specific site unusable. 
![flashbang](https://media1.tenor.com/m/XEiOi9xw07cAAAAC/flashbang.gif)

Could there be a setting like a dampening coefficient that makes it so that very "distant" colors from the current theme (dark) have a reduced influence on the color of the tab bar?

Here is an example: on Google Forms, the form's color is set to blue. This is the result (in dark mode). With this issue corrected, the tab bar would still have a blue tint but still be dark. 
![example1](https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/34781348/f42c8d14-be85-4f3f-aa93-415ee2d0f86e)

Here are my settings
<img width="609" alt="image" src="https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/assets/34781348/06a25b4a-2c33-40a2-bff3-9f085d292a60">

Thank you !

**Comment by CennoxX** [comment]
Is this a duplicate of #58?

**Comment by bensaine** [comment]
> Is this a duplicate of #58?

Possibly. I think we describe the same symptoms but I wonder if a static threshold will be enough to catch all cases. My intuition is that it would need to be a relative calculation based on preferred color theme.

**Comment by bensaine** [comment]
fixed by https://github.com/easonwong-de/Adaptive-Tab-Bar-Colour/pull/75
