### ISSUE TITLE
Ability to only add color to URL bar or tab bar.

### ISSUE THREAD

**Issue by TwisterMc** [easonwong-de/Adaptive-Tab-Bar-Colour#78]
This is a great add-on. I was wondering if we could add the ability to ignore parts of the interface. Possibly a checkbox in each customization section that you can toggle on and off. That way I could only add the color to the URL bar. Or only add color to the Tab Bar.

**Comment by easonwong-de** [comment]
I suggest using a custom CSS theme. For example, if you don’t want the colour of the URL bar being changed, you can add
```
#urlbar-background {
    background-color: var(--a-colour) !important;
}
```
to the CSS theme.
