### ISSUE TITLE
Bookmark overflow menu background is not affected by colour shift.

### ISSUE THREAD

**Issue by adamboulton24** [easonwong-de/Adaptive-Tab-Bar-Colour#81]
When bookmarks are set to always show underneath the toolbar, and the number of bookmarks saved reaches an amount that surpasses the width of the screen, there is an overflow menu that is created to display the bookmarks that don't fit within the screen dimentions. The background of this overflow menu is not affected by the colour shift of this addon, making for an inconsistent appearence.

Just wanted to say this is a great addon and very well done for thinking of and making it. Will be enabled again as soon as this issue is fixed.

**Comment by easonwong-de** [comment]
Hello, @adamboulton24! I apologize for the delayed response and the issue that you have encountered. I couldn’t reproduce the issue you described (shown below). Maybe Firefox’s UI has changed.

![Screenshot 2024-10-30 at 16 56 00](https://github.com/user-attachments/assets/74fdabfa-df9e-4cd7-aa36-b934a029ecc4)

**Comment by adamboulton24** [comment]
I have my custom toolbar colours asigned using the "Firefox Color" extension, whereas I my context menus, including the bookmark overflow dropdown, are manually asigned in my user userchrome.css under "menupopup". I completely forgot about this and just asumed it should override all colours but extensions can't override user css alternations.

Very sorry for wasting your time with this false complaint, I will give this extension another go with this setting disabled 👍
