### ISSUE TITLE
the top bar except the selected tabs dont get colored

### ISSUE THREAD

**Issue by spectrum705** [easonwong-de/Adaptive-Tab-Bar-Colour#82]
![image](https://github.com/user-attachments/assets/c513b18d-cdd5-47b5-97b4-2400c5d96de2)

I tried out changing the settings but the top bar apart from selected tab doesnt get colored for me. 
I am using floorp browser. Is there a way i can fix this and make it work like the demo pics?
Thank you

**Comment by easonwong-de** [comment]
This might be the issue with your CSS theme. The colour of the toolbar seems to have been overwritten by the CSS theme.
