### ISSUE TITLE
[Firefox Nightly]: Not compatible with the new Sidebar

### ISSUE THREAD

**Issue by 0PandaDEV** [easonwong-de/Adaptive-Tab-Bar-Colour#83]
![image](https://github.com/user-attachments/assets/2ae0086d-4399-4368-ab26-5bcf27c3e657)

**Comment by easonwong-de** [comment]
After some testing, I think the new sidebar is getting coloured correctly now. If it still doesn’t on your end, feel free to reopen the issue.
