### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by OutshineIssue** [easonwong-de/Adaptive-Tab-Bar-Colour#90]
I wanted to bring up a couple of accessibility issues I noticed with the sliders for customization.

First, even at the maximum value allowed on the sliders, there's not enough contrast with the background for the active tab. This can make it hard for users with low vision to see what they’re adjusting. The [WCAG guidelines](https://www.w3.org/WAI/WCAG21/quickref/#contrast-minimum) recommend a contrast ratio of at least 3:1 for non-text content and there's currently no option to reach that ratio. This one hits home for me personally, as it can be quite challenging to know exactly which tab is the active one. Please consider increasing the top value so it can go up to a level that provides better contrast for users with low vision.

Also, an actual visual representation of the current value for the sliders would be appreciated. Again, according to the [Web Content Accessibility Guidelines (WCAG)](https://www.w3.org/WAI/WCAG21/quickref/#input-purposes), clear information about the state of controls is super important for accessibility.

**Comment by easonwong-de** [comment]
Thanks for the suggestion!

**Comment by easonwong-de** [comment]
Hi, @OutshineIssue. I added control over contrast ratio and percentage display for the sliders. If you prefer further adjustments, feel free to let me know!

**Comment by OutshineIssue** [comment]
Awesome! I understand that Firefox's approval process can be slow, but I've been keeping an eye on the commits—fantastic job!

By the way, did you encounter any issues with closing #95?

**Comment by easonwong-de** [comment]
Thanks for the follow-up!

I mainly develop on macOS, so I haven’t managed to look into the issue yet. I’ll tackle the issue in the next update, for which I’ll switch to Windows to see what’s up :)
