### ISSUE TITLE
Titlebar will revert to black on Youtube even though I set a custom Color for Youtube

### ISSUE THREAD

**Issue by Pizzateik** [easonwong-de/Adaptive-Tab-Bar-Colour#97]
So, I set a custom Color for YouTube and Fallback in Settings, but when I'm using a YouTube Ambilight extension, the title bar reverts to black, i.e. It still tries to theme the site even though I set a custom color for YouTube
![image](https://github.com/user-attachments/assets/959a1882-0d40-4eff-9041-964e50c54ba7)
![image](https://github.com/user-attachments/assets/99e03470-abb0-4fc8-b0a6-0e752e63ddb4)
![image](https://github.com/user-attachments/assets/069509a7-7525-4df7-86c2-40fdd663e46b)

**Comment by easonwong-de** [comment]
@Pizzateik Thanks for reporting the bug! The “specify a colour” function not working is now a known issue, and the whole settings page will receive a revamp in the next version. I’m sorry for the inconvenience!

**Comment by Pizzateik** [comment]
Oh, no worries, and thanks for addressing it so fast :)

**Comment by easonwong-de** [comment]
Hi, @Pizzateik! A new update (v2.2) is awaiting review from Mozilla, and will be out in a few days. With the update, this issue should have been addressed. If the issue persists, feel free to reopen the issue!
