### ISSUE TITLE
Is it possible to remove the shadow around the selected tab?

### ISSUE THREAD

**Issue by rasitayaz** [easonwong-de/Adaptive-Tab-Bar-Colour#99]
It would be really cool if we could get rid of the shadow around the selected tab.

## Opaque selected tab:
<img width="298" alt="resim" src="https://github.com/user-attachments/assets/ec2274e6-1d85-42bb-94f1-9139a99a71aa">

## Transparent selected tab (for pointing out the shadow):
<img width="279" alt="resim" src="https://github.com/user-attachments/assets/028f2841-60b7-454b-ac11-eec5d63c67b1">

---

Firefox 133.0 (aarch64)
MacOS 15.1.1 (24B91)

**Comment by easonwong-de** [comment]
Hello! @rasitayaz, it’s only achievable with custom CSS theme.

```
.tab-background:is([selected], [multiselected]) {
    box-shadow: none !important;
}
```

With the CSS theme:

![Screenshot 2024-12-06 at 20 32 14](https://github.com/user-attachments/assets/29d88fb3-0c8d-4319-af6f-51f109af6653)

**Comment by rasitayaz** [comment]
thanks a bunch!
